[package]
name = "rustytransfer"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anyhow = "1.0.100"
futures-util = "0.3.31"
serde = { version = "1.0.228", features = ["derive"]}
serde_json = "1.0.145"
spake2 = "0.4.0"
url = "2.5.7"
uuid = "1.19.0"
wasm-bindgen = "0.2.106"

getrandom = { version = "0.3", features = ["wasm_js"] }
getrandom02 = { package = "getrandom", version = "0.2", features = ["js"] }
js-sys = "0.3.83"
ml-kem = "0.2.1"
rand_core = "0.6.4"
aes-gcm = { version = "0.10.3", features = ["aes"] }
rand = "0.8.5"
hmac = "0.12.1"
sha3 = "0.10.8"
bytes = "1.11.0"
clap = { version = "4", features = ["derive"] }
indicatif = "0.18.3"
ratatui = { version = "0.29.0", features = ["unstable-widget-ref"] }
crossterm = "=0.28.1"
ratatui-explorer = "0.2.1"

# --- NATIVE ONLY DEPENDENCIES ---
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
just-webrtc = "0.2.0"
reqwest = { version = "0.12", features = ["json", "blocking"]}
tokio = { version = "1.48.0", features = ["rt-multi-thread", "macros"] }
tokio-tungstenite = { version = "0.28.0", features = ["rustls-tls-webpki-roots", "url"] }
webrtc = "0.14.0"

[[bin]]
name = "rustytransfer"
path = "src/bin/rustytransferCLI.rs"

#wasm-pack build --target web --out-dir ../astro/src/wasm/rustytransfer --out-name rustytransfer

[lints.clippy]
allow_attributes = "warn"
allow_attributes_without_reason = "warn"
arithmetic_side_effects = "warn"
as_conversions = "warn"
assertions_on_result_states = "warn"
await_holding_lock = "warn"
await_holding_refcell_ref = "warn"
cast_possible_truncation = "warn"
cast_possible_wrap = "warn"
cast_precision_loss = "warn"
cast_sign_loss = "warn"
dbg_macro = "warn"
debug_assert_with_mut_call = "warn"
default_trait_access = "warn"
expect_used = "warn"
expl_impl_clone_on_copy = "warn"
explicit_iter_loop = "warn"
float_cmp = "warn"
float_cmp_const = "warn"
get_unwrap = "warn"
if_let_mutex = "warn"
indexing_slicing = "warn"
invalid_upcast_comparisons = "warn"
iter_not_returning_iterator = "warn"
large_enum_variant = "warn"
large_futures = "warn"
let_underscore_future = "warn"
let_underscore_must_use = "warn"
lossy_float_literal = "warn"
map_err_ignore = "warn"
match_same_arms = "warn"
match_wildcard_for_single_variants = "warn"
mem_forget = "warn"
missing_errors_doc = "warn"
missing_panics_doc = "warn"
module_name_repetitions = "warn"
multiple_unsafe_ops_per_block = "warn"
must_use_candidate = "warn"
needless_continue = "warn"
no_effect_underscore_binding = "warn"
no_mangle_with_rust_abi = "warn"
not_unsafe_ptr_arg_deref = "warn"
panic = "warn"
panic_in_result_fn = "warn"
pedantic = "warn"
rc_mutex = "warn"
result_large_err = "warn"
return_self_not_must_use = "warn"
similar_names = "warn"
single_match_else = "warn"
string_slice = "warn"
struct_field_names = "warn"
todo = "warn"
unchecked_time_subtraction = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
uninlined_format_args = "warn"
unnecessary_safety_comment = "warn"
unnecessary_safety_doc = "warn"
unreachable = "warn"
unused_result_ok = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"
wildcard_imports = "warn"
