[package]
name = "rustytransfer-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
rustytransfer-crypto = { version = "0.1.0", path = "../crypto" }
rustytransfer-protocol = { version = "0.1.0", path = "../protocol" }
wasm-bindgen.workspace = true

[lints]
workspace = true
