[package]
name = "rustytransfer-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
spake2.workspace = true
ml-kem.workspace = true
rand_core.workspace = true
aes-gcm.workspace = true
hmac.workspace = true
sha3.workspace = true

[target.'cfg(target_arch = "wasm32")'.dependencies]
getrandom = { workspace = true, features = ["wasm_js"] }
getrandom02 = { workspace = true, features = ["js"] }

[lints]
workspace = true
